CREATE DATABASE [VENDAS SUCOS];

CREATE DATABASE [VENDAS SUCOS 2] 
ON (
    NAME = 'VENDAS_SUCOS_2_DAT', 
    FILENAME ='C:\TEMP\VENDAS_SUCOS_02.MDF', 
    SIZE = 10, 
    MAXSIZE = 50, 
    FILEGROWTH = 5
);

CREATE TABLE PRODUTOS (
    CODIGO VARCHAR(10) NOT NULL, 
    DESCRITOR VARCHAR(100) NULL, 
    SABOR VARCHAR(50) NULL, 
    TAMANHO VARCHAR(50) NULL, 
    EMBALAGEM VARCHAR(50) NULL, 
    PRECO_LISTA FLOAT NULL, 
    PRIMARY KEY (CODIGO)
);
cREATE TABLE CLIENTES
(
CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(100) NULL,
ENREDECO VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
CIDADE VARCHAR(50) NULL,
ESTADO VARCHAR(50) NULL,
CEP VARCHAR(8) NULL,
DATA_NASCIMENTO DATE NULL,
IDADE INTEGER NULL,
GENERO VARCHAR(1) NULL,
LIMITE_CREDITO FLOAT,
VOLUME_COMPRA FLOAT,
PRIMAIRA_COMPRA BIT,
PRIMARY KEY (CPF)
);

CREATE TABLE TABELA_DE_VENDAS (
    NUMERO VARCHAR(5) NOT NULL, 
    DATA_VENDA DATE NULL, 
    CPF VARCHAR(11) NOT NULL, 
    MATRICULA VARCHAR(11) NOT NULL, 
    IMPOSTO FLOAT NULL, 
    PRIMARY KEY (NUMERO)
);

ALTER TABLE TABELA_DE_VENDAS 
ADD CONSTRAINT FK_VENDEDORES 
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA);

